# Generated by Django 4.2.14 on 2024-08-09 22:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Large Size Grooming', 'Large Size Grooming'), ('Medium Size Grooming', 'Medium Size Grooming'), ('Small Size Grooming', 'Small Size Grooming'), ('Bath + Blowdry (Under 25 lbs)', 'Bath + Blowdry (Under 25 lbs)'), ('Bath + Blowdry (Over 25 lbs)', 'Bath + Blowdry (Over 25 lbs)')], default='Grooming Service', max_length=50)),
                ('day', models.DateField(default=datetime.datetime.now)),
                ('time', models.CharField(choices=[('10 AM', '10 AM'), ('11 AM', '11 AM'), ('12 PM', '12 PM'), ('2 PM', '2 PM'), ('3 PM', '3 PM'), ('4 PM', '4 PM'), ('5 PM', '5 PM'), ('7 PM', '7 PM')], default='10 AM', max_length=10)),
                ('time_ordered', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
