# Generated by Django 4.2.14 on 2024-09-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='groomers',
            field=models.ManyToManyField(related_name='services', to='booking.groomer'),
        ),
    ]
